### ISSUE TITLE
Add instruction to add this library into android

### ISSUE THREAD

**Issue by dIvYaNshhh** [neevek/rstun#2]
Ad per the code, it seems like this lib is compatible for android
Is it possible to add some instruction to consume this lib into android?

**Comment by neevek** [comment]
> Ad per the code, it seems like this lib is compatible for android Is it possible to add some instruction to consume this lib into android?

The lib can simply be compiled as a `.so` file and used in Android through JNI. Currently the JNI method names and NDK config are hardcoded, you may try to change that, I don't have time to work on this recently, maybe some time later...
