### ISSUE TITLE
Is there any possibility to support musl libc?

### ISSUE THREAD

**Issue by aa51513** [neevek/rstun#3]
I try to run rstunc on Openwrt with x86/64 arch, but it doesn't work.

The error message is as follows:
```
Error relocating rstunc: __register_atfork: symbol not found
Error relocating rstunc: __res_init: symbol not found
Error relocating rstunc: gnu_get_libc_version: symbol not found
```

It looks like rstunc failed in its attempt to reference gun libc

In my scene, openwrt does not contain gun libc, instead it is musl libc
I run `ldd --version` and then I got 
```
musl libc (x86_64)
Version 1.2.4
Dynamic Program Loader
```

Is there any possibility to support musl libc?

**Comment by neevek** [comment]
I don't have the environment to test it now, you may build it yourself and try it in your environment and report back the result, or if it works you may send a PR for modifying the github actions to support `musl` target.

```
cargo build --release --target=musl
```

**Comment by aa51513** [comment]
> I don't have the environment to test it now, you may build it yourself and try it in your environment and report back the result, or if it works you may send a PR for modifying the github actions to support `musl` target.
> 
> ```
> cargo build --release --target=musl
> ```

I tried to compile the master branch code on Alpine using the following command: 
`cargo build --release --target=x86_64-unknown-linux-musl`,
it works !


Does this mean that it is a good idea to add the musl build instructions to the GitHub build action?

**Comment by neevek** [comment]
Thank you for the feedback, I just updated the build actions and released a new revision for musl.
Check it out here: https://github.com/neevek/rstun/releases/tag/release%2F0.4.15
