### ISSUE TITLE
support using domain to connect to the server with self-signed certificate 

### ISSUE THREAD

**Issue by aa51513** [neevek/rstun#4]
Due to the broadband line, I don't have a fixed IP address, so I use DDNS to access the Raspberry Pi at home.

This caused a problem, I couldn't connect to rstund with a self-signed certificate because of the lack of a fixed IP.

Maybe specifying the self-signed ca certificate on the client can perfectly solve this problem.

**Comment by neevek** [comment]
Current implementation will ignore self-signed certificate if you connect to rstund using a domain. I think the request makes sense, I will add support for that in next release some time this month.

**Comment by neevek** [comment]
> Maybe specifying the self-signed ca certificate on the client can perfectly solve this problem.

This is supported in the latest release.

**Comment by aa51513** [comment]
> > Maybe specifying the self-signed ca certificate on the client can perfectly solve this problem.
> 
> This is supported in the latest release.

It works, I love your work, it’s simply awesome
