### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by aguasonic** [neevek/rstun#6]
Trying to build rstun:

error[E0282]: type annotations needed for `Box<_>`
  --> mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error

**Comment by neevek** [comment]
@aguasonic It's a dependency issue that causes compilation error with the latest toolchain (1.80.0), now fixed.
